### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by mikoczy** [remp2020/crm-coupon-module#1]
Hi,
first, thanks for your work.
I've tried to install this library, but it looks like a migration is missing.. There is a repository for table coupons, but the table does not exist. Could you please look into it?

Thanks

**Comment by rootpd** [comment]
Thanks for the report! We'll look into it, it really is missing.

We're working at some improvements of the coupon module (generator of coupons, some missing widgets around the system) so we'll issue a release with all the other changes. Hopefully it should be ready by the end of this week (worst case beginning of next).

**Comment by rootpd** [comment]
We've just released `v0.10.0` of all the modules, changes include missing migration and some base features that were missing in coupons module. There's still no API/page for activation, this will be part of `v0.11.0`.
